version: '3.9'

services:
  ror7:
    build: .
    container_name: ror7api
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - .env/development/database
      - .env/development/ror7
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - database
      - redis
    networks:
      - ror7api-network

  redis:
    image: redis:7.0.9
    command: redis-server
    container_name: ror7api-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ror7api-network

  database:
    image: postgres:15.2-alpine
    container_name: ror7api-database
    restart: unless-stopped
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ror7api-network

volumes:
  db_data:
  redis_data:

networks:
  ror7api-network:
    driver: bridge # defaulted
